services:
    schedule_bundle.command.schedule:
        class: Adamski\Symfony\ScheduleBundle\Command\ScheduleCommand
        arguments:
            - "@schedule_bundle.manager"
            - "@lock.default.factory"
        tags:
            - { name: console.command, command: 'schedule:run' }

    Adamski\Symfony\ScheduleBundle\Command\ScheduleCommand:
        alias: schedule_bundle.command.schedule
